Rewrite some scripts for better consistency

diff --git a/local/bin/dhcp-server b/local/bin/dhcp-server
--- a/local/bin/dhcp-server
+++ b/local/bin/dhcp-server
@@ -1,27 +1,51 @@
-#!/bin/bash
-# Check /etc/bootpd.plist for DHCP parameters
-if [[ $OSTYPE == "darwin"* ]]; then
-	select name in StartDHCP StopDHCP Exit ;
-	do
-		case "$name" in
-			StartDHCP)
-	            sudo /bin/launchctl load -w /System/Library/LaunchDaemons/bootps.plist
-				echo
-				echo "DHCP server started. Modify its options in /etc/bootpd.list"
-				echo
-	            break
-	          ;;
-	        StopDHCP)
-	            sudo /bin/launchctl unload -w /System/Library/LaunchDaemons/bootps.plist
-				echo
-				echo "DHCP server stopped"
-				echo
-	            break
-	          ;;
-	        Exit)
-	            exit 0
-	            break
-	            ;;
-		esac
-	done
+#!/usr/bin/env bash
+#===================================================
+# Author: Gaetan (gaetan@ictpourtous.com)
+# Creation: Mon Aug 2021 14:57:49
+# Last modified: Mon Aug 2021 14:57:49
+# Version: 1.0
+#
+# Description: Start/stop local DHCP server
+#===================================================
+
+#=======================
+# Requirements
+#=======================
+if [[ "$EUID" != 0 ]] && ! type sudo > /dev/null 2>&1; then
+	echo .
+	echo "Root privileges are required to run this script. Make sure to execute the script as root or have sudo installed!"
+	exit 2
 fi
+
+#=======================
+# Functions
+#=======================
+startDHCP() {
+if [[ $OSTYPE == "darwin"* ]]; then
+	sudo /bin/launchctl load -w /System/Library/LaunchDaemons/bootps.plist
+	echo "DHCP server started. Modify its options in /etc/bootpd.list"
+fi
+}
+
+stopDHCP() {
+if [[ $OSTYPE == "darwin"* ]]; then
+	sudo /bin/launchctl unload -w /System/Library/LaunchDaemons/bootps.plist
+	echo "DHCP server stopped"
+fi
+}
+
+#=======================
+# DHCP
+#=======================
+case "$1" in
+	"--start") startDHCP ;;
+	"--stop") stopDHCP ;;
+	*)
+		echo "An action needs to be specified!
+Usage: dhcp-server <ARGUMENT>
+	--start: start the local DHCP server
+	--stop: stop the local DHCP server
+	"
+	exit 1
+	;;
+esac
diff --git a/local/bin/tftp-server b/local/bin/tftp-server
--- a/local/bin/tftp-server
+++ b/local/bin/tftp-server
@@ -1,27 +1,51 @@
-#!/bin/bash
-# Start the built-in TFTP server in macOS. Root is located at /private/tftpboot
-if [[ $OSTYPE == "darwin"* ]]; then
-	select name in StartTFTP StopTFTP Exit ;
-	do
-		case "$name" in
-			StartTFTP)
-	            sudo launchctl load -F /System/Library/LaunchDaemons/tftp.plist
-				echo
-				echo "TFTP server started. The root is located in /private/tftpboot"
-				echo
-	            break
-	          ;;
-	        StopTFTP)
-	            sudo launchctl unload -F /System/Library/LaunchDaemons/tftp.plist
-				echo
-				echo "TFTP server stopped"
-				echo
-	            break
-	          ;;
-	        Exit)
-	            exit 0
-	            break
-	            ;;
-		esac
-	done
+#!/usr/bin/env bash
+#===================================================
+# Author: Gaetan (gaetan@ictpourtous.com)
+# Creation: Mon Aug 2021 14:57:49
+# Last modified: Mon Aug 2021 14:57:49
+# Version: 1.0
+#
+# Description: Start/stop local TFTP server
+#===================================================
+
+#=======================
+# Requirements
+#=======================
+if [[ "$EUID" != 0 ]] && ! type sudo > /dev/null 2>&1; then
+	echo .
+	echo "Root privileges are required to run this script. Make sure to execute the script as root or have sudo installed!"
+	exit 2
 fi
+
+#=======================
+# Functions
+#=======================
+startTFTP() {
+if [[ $OSTYPE == "darwin"* ]]; then
+	sudo launchctl load -F /System/Library/LaunchDaemons/tftp.plist
+	echo "TFTP server started. The root is located in /private/tftpboot"
+fi
+}
+
+stopTFTP() {
+if [[ $OSTYPE == "darwin"* ]]; then
+	sudo launchctl unload -F /System/Library/LaunchDaemons/tftp.plist
+	echo "TFTP server stopped"
+fi
+}
+
+#=======================
+# TFTP
+#=======================
+case "$1" in
+	"--start") startTFTP ;;
+	"--stop") stopTFTP ;;
+	*)
+		echo "An action needs to be specified!
+Usage: tftp-server <ARGUMENT>
+	--start: start the local TFTP server
+	--stop: stop the local TFTP server
+	"
+	exit 1
+	;;
+esac
diff --git a/local/bin/upcloud-manager b/local/bin/upcloud-manager
--- a/local/bin/upcloud-manager
+++ b/local/bin/upcloud-manager
@@ -1,52 +1,81 @@
-#!/bin/bash
-# Allow to either start or stop servers hosted at UpCloud
-select name in "Start server" "Stop server" "Check server status" "Get server details" "Exit" ;
-do
-	case "$name" in
-		"Start server")
-			echo
-			read -spr "Enter your Base64 encoded API key: " APIKEY
-			echo
-			read -rp "Server's UUID: " SRVUUID
-			curl -s -i -X POST -H "Authorization:Basic $APIKEY" "https://api.upcloud.com/1.3/server/$SRVUUID/start" > /dev/null 2>&1
-			echo
-			echo "The server $SRVUUID has been started"
-			break
-		;;
-		"Stop server")
-			echo
-			read -spr "Enter your Base64 encoded API key: " APIKEY
-			echo
-			read -rp "Server's UUID: " SRVUUID
-			curl -s -i -X POST -H "Authorization:Basic $APIKEY" "https://api.upcloud.com/1.3/server/$SRVUUID/stop" > /dev/null 2>&1
-			echo
-			echo "The server $SRVUUID has been stopped"
-			break
-		;;
-		"Check server status")
-			echo
-			read -spr "Enter your Base64 encoded API key: " APIKEY
-			echo
-			read -rp "Server's UUID: " SRVUUID
-			srvstatus=$(curl -s -i -X GET -H "Authorization:Basic $APIKEY" "https://api.upcloud.com/1.3/server/$SRVUUID" | grep state)
-			if [[ "$srvstatus" == *"stopped"* ]]; then
-				echo "The server $SRVUUID is currently powered off"
-			else
-				echo "The server $SRVUUID is currently powered on"
-			fi
-			break
-		;;
-		"Get server details")
-			echo
-			read -spr "Enter your Base64 encoded API key: " APIKEY
-			echo
-			read -rp "Server's UUID: " SRVUUID
-			curl -s -i -X GET -H "Authorization:Basic $APIKEY" "https://api.upcloud.com/1.3/server/$SRVUUID"
-			break
-		;;
-		"Exit")
-			exit 0
-			break
-			;;
-	esac
-done
+#!/usr/bin/env bash
+#===================================================
+# Author: Gaetan (gaetan@ictpourtous.com)
+# Creation: Tue Aug 2021 22:58:12
+# Last modified: Tue Aug 2021 22:58:12
+# Version: 1.0
+#
+# Description: Manage servers hosted at UpCloud
+#===================================================
+
+#=======================
+# Requirements
+#=======================
+if ! type curl > /dev/null 2>&1; then
+	echo .
+	echo "Curl is not installed. Please install 'curl'!"
+	exit 2
+fi
+
+#=======================
+# Functions
+#=======================
+startServer() {
+	echo
+	read -sp "Enter your Base64 encoded API key: " APIKEY
+	echo
+	read -p "Server's UUID: " SRVUUID
+	curl -s -i -X POST -H "Authorization:Basic $APIKEY" "https://api.upcloud.com/1.3/server/$SRVUUID/start" > /dev/null 2>&1 &&	echo && echo "The server $SRVUUID has been started"
+}
+
+stopServer() {
+	echo
+	read -sp "Enter your Base64 encoded API key: " APIKEY
+	echo
+	read -p "Server's UUID: " SRVUUID
+	curl -s -i -X POST -H "Authorization:Basic $APIKEY" "https://api.upcloud.com/1.3/server/$SRVUUID/stop" > /dev/null 2>&1 && echo && echo "The server $SRVUUID has been stopped"
+}
+
+checkServer(){
+	echo
+	read -sp "Enter your Base64 encoded API key: " APIKEY
+	echo
+	read -p "Server's UUID: " SRVUUID
+	curl -s -i -X GET -H "Authorization:Basic $APIKEY" "https://api.upcloud.com/1.3/server/$SRVUUID"
+}
+
+checkServerStatus(){
+	echo
+	read -sp "Enter your Base64 encoded API key: " APIKEY
+	echo
+	read -p "Server's UUID: " SRVUUID
+	srvstatus=$(curl -s -i -X GET -H "Authorization:Basic $APIKEY" "https://api.upcloud.com/1.3/server/$SRVUUID" | grep state)
+	if [[ "$srvstatus" == *"stopped"* ]]; then
+		echo "The server $SRVUUID is currently powered off"
+	elif [[ "$srvstatus" == *"started"* ]]; then
+		echo "The server $SRVUUID is currently powered on"
+	else
+		echo "An error occurred"
+		exit 3
+	fi
+}
+
+#=======================
+# API Calls
+#=======================
+case "$1" in
+	"--start") startServer ;;
+	"--stop") stopServer ;;
+	"--check") checkServer ;;
+	"--status") checkServerStatus ;;
+	*)
+		echo "An action needs to be specified!
+Usage: upcloud-manager --{start|stop|check|status}
+	--start: start a remote server
+	--stop: stop a remote server
+	--check: get details of a remote server
+	--status: get the status of a remote server
+	"
+	exit 1
+	;;
+esac
