Prevent 'update-system' alias to end up with an error code if reboot is not required

diff --git a/shellconfig/apps_aliases b/shellconfig/apps_aliases
--- a/shellconfig/apps_aliases
+++ b/shellconfig/apps_aliases
@@ -84,19 +84,19 @@ elif [[ $OSTYPE == "linux-gnu" ]]; then
 
 	# Debian based systems using APT or APT-GET package manager
 	if type apt snap > /dev/null 2>&1; then
-		alias update-system='sudo apt update && sudo apt upgrade && sudo apt full-upgrade && sudo apt autoremove --purge && sudo apt autoclean && sudo apt clean && { test -f /var/run/reboot-required && echo -e "$FILE \033[31mA reboot is required to apply all updates"; } ; sudo snap refresh'
+		alias update-system='sudo apt update && sudo apt upgrade && sudo apt full-upgrade && sudo apt autoremove --purge && sudo apt autoclean && sudo apt clean && { test -f /var/run/reboot-required && echo -e "$FILE \033[31mA reboot is required to apply all updates" || true; } ; sudo snap refresh'
 	elif type apt > /dev/null 2>&1; then
-		alias update-system='sudo apt update && sudo apt upgrade && sudo apt full-upgrade && sudo apt autoremove --purge && sudo apt autoclean && sudo apt clean && { test -f /var/run/reboot-required && echo -e "$FILE \033[31mA reboot is required to apply all updates"; }'
+		alias update-system='sudo apt update && sudo apt upgrade && sudo apt full-upgrade && sudo apt autoremove --purge && sudo apt autoclean && sudo apt clean && { test -f /var/run/reboot-required && echo -e "$FILE \033[31mA reboot is required to apply all updates" || true; }'
 	elif type apt-get snap > /dev/null 2>&1; then
-		alias update-system='sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade && sudo apt-get autoremove --purge && sudo apt-get autoclean && sudo apt-get clean && { test -f /var/run/reboot-required && echo -e "$FILE \033[31mA reboot is required to apply all updates"; } ; sudo snap refresh'
+		alias update-system='sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade && sudo apt-get autoremove --purge && sudo apt-get autoclean && sudo apt-get clean && { test -f /var/run/reboot-required && echo -e "$FILE \033[31mA reboot is required to apply all updates" || true; } ; sudo snap refresh'
 	elif type apt-get > /dev/null 2>&1; then
-		alias update-system='sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade && sudo apt-get autoremove --purge && sudo apt-get autoclean && sudo apt-get clean && { test -f /var/run/reboot-required && echo -e "$FILE \033[31mA reboot is required to apply all updates"; }'
+		alias update-system='sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade && sudo apt-get autoremove --purge && sudo apt-get autoclean && sudo apt-get clean && { test -f /var/run/reboot-required && echo -e "$FILE \033[31mA reboot is required to apply all updates" || true; }'
 
 	# Red Hat based systems using DNF package manager
 	elif type dnf snap > /dev/null 2>&1; then
-		alias update-system='sudo dnf update && sudo dnf autoremove && sudo dnf clean all && sudo dnf remove --oldinstallonly --setopt installonly_limit=2 kernel && { needs-restarting -r; if [ $? -eq 1 ]; then echo -e "\033[31mA reboot is required to apply all updates"; fi; } ; sudo snap refresh'
+		alias update-system='sudo dnf update && sudo dnf autoremove && sudo dnf clean all && sudo dnf remove --oldinstallonly --setopt installonly_limit=2 kernel && { needs-restarting -r; if [ $? -eq 1 ]; then echo -e "\033[31mA reboot is required to apply all updates"; fi || true; } ; sudo snap refresh'
 	elif type dnf > /dev/null 2>&1; then
-		alias update-system='sudo dnf update && sudo dnf autoremove && sudo dnf clean all && sudo dnf remove --oldinstallonly --setopt installonly_limit=2 kernel && { needs-restarting -r; if [ $? -eq 1 ]; then echo -e "\033[31mA reboot is required to apply all updates"; fi; }'
+		alias update-system='sudo dnf update && sudo dnf autoremove && sudo dnf clean all && sudo dnf remove --oldinstallonly --setopt installonly_limit=2 kernel && { needs-restarting -r; if [ $? -eq 1 ]; then echo -e "\033[31mA reboot is required to apply all updates"; fi || true; }'
 
 	# Red Hat based systems using YUM package manager
 	elif type yum snap > /dev/null 2>&1; then
